### ISSUE TITLE
Fuzzy Systray Icon

### ISSUE THREAD

**Issue by edent** [SwagDevOps/elementary-wicd-icons#1]
Thanks for the easy install script. It all worked well.

The only small problem is that my panel is 48px high - and the new WICD logo looks a bit fuzzy compared to the other logos.

![wicd](https://user-images.githubusercontent.com/837136/27514270-b36d9e6c-597d-11e7-8205-6c8918e3356b.png)

Is it possible to use an SVG or something higher resolution?

Using MATE Ubuntu 17.04

**Comment by SwagDevOps** [comment]
Almost a bug due to wicd? Isn't it? 
You should try a 48px high panel using native wicd icons.

**Comment by edent** [comment]
That's the icon I got once I installed the elementary-wicd-icons.  I'm not sure how I go back to the original set.

**Comment by SwagDevOps** [comment]
`sudo apt install --reinstall wicd-gtk`

**Comment by edent** [comment]
Yeah, still a bit fuzzy.
![zz](https://user-images.githubusercontent.com/837136/27796674-c04bbfc0-6002-11e7-8ad8-5e3fc6ea9249.png)

**Comment by SwagDevOps** [comment]
IMHO there is nothing I can do… 
seems to be a bug from `wicd-gtk` or the panel (kind of systray applet), or both.
